//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAVinCustHost.CustOrders {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VPIOrder", Namespace="http://schemas.datacontract.org/2004/07/VinCustOrders")]
    [System.SerializableAttribute()]
    public partial class VPIOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdvertiserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsrEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CsrNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Advertiser {
            get {
                return this.AdvertiserField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvertiserField, value) != true)) {
                    this.AdvertiserField = value;
                    this.RaisePropertyChanged("Advertiser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CsrEmail {
            get {
                return this.CsrEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CsrEmailField, value) != true)) {
                    this.CsrEmailField = value;
                    this.RaisePropertyChanged("CsrEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CsrName {
            get {
                return this.CsrNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CsrNameField, value) != true)) {
                    this.CsrNameField = value;
                    this.RaisePropertyChanged("CsrName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Design {
            get {
                return this.DesignField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignField, value) != true)) {
                    this.DesignField = value;
                    this.RaisePropertyChanged("Design");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineNumber {
            get {
                return this.LineNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LineNumberField, value) != true)) {
                    this.LineNumberField = value;
                    this.RaisePropertyChanged("LineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNumber {
            get {
                return this.PoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNumberField, value) != true)) {
                    this.PoNumberField = value;
                    this.RaisePropertyChanged("PoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivedBy {
            get {
                return this.ReceivedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedByField, value) != true)) {
                    this.ReceivedByField = value;
                    this.RaisePropertyChanged("ReceivedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingMethod {
            get {
                return this.ShippingMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingMethodField, value) != true)) {
                    this.ShippingMethodField = value;
                    this.RaisePropertyChanged("ShippingMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingNumber {
            get {
                return this.TrackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingNumberField, value) != true)) {
                    this.TrackingNumberField = value;
                    this.RaisePropertyChanged("TrackingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustOrders.CustomerOrders")]
    public interface CustomerOrders {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerOrders/GetOrders", ReplyAction="http://tempuri.org/CustomerOrders/GetOrdersResponse")]
        CAVinCustHost.CustOrders.VPIOrder[] GetOrders(string companyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerOrders/GetOrder", ReplyAction="http://tempuri.org/CustomerOrders/GetOrderResponse")]
        CAVinCustHost.CustOrders.VPIOrder GetOrder(string companyCode, string ordernu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerOrdersChannel : CAVinCustHost.CustOrders.CustomerOrders, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerOrdersClient : System.ServiceModel.ClientBase<CAVinCustHost.CustOrders.CustomerOrders>, CAVinCustHost.CustOrders.CustomerOrders {
        
        public CustomerOrdersClient() {
        }
        
        public CustomerOrdersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerOrdersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerOrdersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerOrdersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CAVinCustHost.CustOrders.VPIOrder[] GetOrders(string companyCode) {
            return base.Channel.GetOrders(companyCode);
        }
        
        public CAVinCustHost.CustOrders.VPIOrder GetOrder(string companyCode, string ordernu) {
            return base.Channel.GetOrder(companyCode, ordernu);
        }
    }
}
